package io.github.LucasMullerC.Util;

public class Mensagens {
    public static String Link1 = "Sua conta não está linkada ao Discord, Siga os passos abaixo:";
    public static String Link2 = "1 - Entre em nosso Discord: ";
    public static String Link3 = "2 - Digite ";
    public static String Link4 = "/link SeuNicknoDiscord#1234";
    public static String Link5 = " no chat do Minecraft e siga as próximas instruções. :)";
    public static String Link1en = "Your account is not linked to your Discord, Follow the steps below:";
    public static String Link2en = "1 - Join our Discord: ";
    public static String Link3en = "2 - Type ";
    public static String Link4en = "/link YourDiscordNick#1234";
    public static String Link5en = " and send the code to our bot. :)";
    public static String Link6 = "A conta que você está linkado não foi encontrada, Entre em nosso servidor do Discord:";
    public static String InviteDiscord = "https://discord.gg/F6EQM8VbRy";
    public static String Isconstrutor = "Você já é um construtor neste time!";
    public static String Notconstrutor = "Você não é um construtor do time selecionado!";
    public static String AplicacaoAndamento = "Você já tem uma aplicação em andamento!";
    public static String NenhumaAplicacao = "Você não tem nenhuma aplicação em andamento.";
    public static String NenhumaAplicacaoPlayer = "Player não tem nenhuma aplicação em andamento";
    public static String AplicacaoAndamento2 = "Digite /cancelar para cancelar sua aplicação pendente ou /continuar para continuar o processo.";
    public static String invalido = "Inválido";
    public static String NotDiscord = "Você precisa entrar no Discord do time que deseja participar para continuar a aplicação.";
    public static String AppInit = "Aplicação iniciada!";
    public static String AppSec1 = "Assista o vídeo e siga as instruções: https://youtu.be/KEvtqOYDatE";
    public static String AppSec2 = "Assista o video e siga as instruções: https://www.youtube.com/watch?v=CMHG-txFpEc";
    public static String AppSec3 = "Assista o video e siga as instruções: https://www.youtube.com/watch?v=gajlcoGs6Ro";
    public static String AppSec4 = "Assista o video e siga as instruções: https://www.youtube.com/watch?v=f9mAnVJvqXU";
    public static String AppSec5 = "IMGUR: https://imgur.com/  | So digite /completo após enviar a print e completar o formulario na pagina de cadastro do time.";
    public static String AppTerr = "A altura correta deste terreno está no Y: 32, Ajuste!";
    public static String AppProx = "Você não tem nenhuma aplicação em andamento.";
    public static String GoogleMaps = "Link para o Google Maps: https://goo.gl/maps/uTwZwvUUh7u3jutj9";
    public static String AppCont = "Você já está na ultima área! Digite /Completo para finalizar.";
    public static String AppAnt = "Você está na primeira área! Digite /proximo para seguir em frente.";
    public static String AppRemind = "Lembre-se de seguir as instruções dos videos!";
    public static String AppEnviada = "Sua aplicação foi enviada para o Time que você escolheu e logo será analisada!";
    public static String AnalisePend = "Você já tem uma analise pendente!";
    public static String PendenteMsg = "Existem aplicações para serem analisadas, Se estiver disponivel entre na network e digite **/analisar**";
    public static String NotCompleto = "Você ainda não terminou a Aplicação! Digite /proximo para passar para a próxima zona.";
    public static String Tagadd = "Tag adicionada!";
    public static String TagRemove = "Tag removida!";
    public static String NotAnalisar = "Seu time não tem nenhuma aplicação pendente.";
    public static String ZonaDel = "Aguarde! A zona de Aplicação está sendo removida.";
    public static String ZonaDel1 = "Zona removida com sucesso!";
    public static String AppAprov = "Aplicação aprovada! Builder adicionado!";
    public static String AppAprovBuilder = "Sua aplicação foi aprovada! Agora você é um builder oficial!";
    public static String AppRecusada1 = "Sua aplicação foi recusada pelo motivo: ";
    public static String AppRecusada2 = " | Volte até lá e corrija os problemas!";
    public static String AppRecusada3 = "Aplicação recusada!";
    public static String Analisar1 = "Digite /analisar confirmar - Para aceitar a aplicação.";
    public static String Analisar2 = "Ou digite /analisar recusar (Motivo) - Para recusar a aplicação.";
    public static String ErroCancelar = "Ocorreu um erro. [2]";
    public static String Perm1 = "Você não tem permissão para usar este comando!";
    public static String addEquipe1 = "/addequipe Nick_Mine";
    public static String PlayerOn = "O jogador deve estar Online!";
    public static String Equipe1 = "Jogador adicionado a equipe!";
    public static String Equipe2 = "O Jogador já faz desta equipe!";
    public static String Equipe3 = "/removerequipe UUID";
    public static String EquipeRemove = "Jogador removido da sua equipe!";
    public static String EquipeNotFound = "Jogador não encontrado ou não faz parte da sua equipe!";
    public static String LinkDiscord = "Digite aqui o código enviado no chat do Minecraft.";
    public static String PerfilNotBuilder = "Você não é construtor em nenhum time :(, Porque não se junta á nós?";
    public static String Atencao = "ATENÇÃO!";
    public static String SeuTime1 = "Seu time tem (";
    public static String SeuTime2 = ") aplicações pendentes, Digite";
    public static String analisar = "/analisar";
    public static String Bnovamente = "Bem-vindo novamente ";
    public static String TimesUp = "Sua aplicação foi automaticamente cancelada por inatividade.";
    public static String TimesUpAdm = " Aplicações foram canceladas automaticamente por inatividade.";
    public static String VoceAnalisa = "Você está analisando a aplicação de ";
    public static String VoceAnalisa2 = ", Discord: ";
}
